# Generated by Django 4.2.9 on 2025-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Carriage', 'Carriage'), ('Drawings', 'Drawings'), ('Wages', 'Wages'), ('Renumeration', 'Renumeration'), ('Electric Bill', 'Electric Bill'), ('Rent', 'Rent'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=20, verbose_name='Expense Type')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('incurred_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-incurred_on'],
            },
        ),
    ]
