# Generated by Django 4.2.9 on 2026-01-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_delete_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bill_amount',
            field=models.FloatField(default=0),
        ),
    ]
