# Generated by Django 4.2.9 on 2026-01-20 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sales_sold_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sold_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
