# Generated by Django 4.2.9 on 2026-01-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sales_sold_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sold_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
